"""Add E2E business logic fields

Revision ID: 6346f8f1dbc4
Revises: 87be89210051
Create Date: 2026-08-12 14:32:10.827872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6346f8f1dbc4'
down_revision: Union[str, None] = '87be89210051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passing_percentage', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('question_timer_seconds', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_certificate_eligible', sa.Boolean(), nullable=False))

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('qr_code_hash', sa.String(length=255), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_mode', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('meeting_provider', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('meeting_provider')
        batch_op.drop_column('delivery_mode')

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_column('qr_code_hash')
        batch_op.drop_column('check_in_status')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('is_certificate_eligible')
        batch_op.drop_column('max_attempts')
        batch_op.drop_column('question_timer_seconds')
        batch_op.drop_column('passing_percentage')

    # ### end Alembic commands ###
